# SDD Quality Configuration
# Validation configuration for the Spec-Driven Development system

[validation]
enabled = true
fail_fast = false          # Continue validation even if one check fails
timeout = 1800            # Maximum validation time in seconds
parallel = true           # Run independent checks in parallel

[testing]
enabled = true
runner = "pytest"         # Test runner command
config_file = "pytest.ini"  # Optional test configuration
coverage_threshold = 80   # Minimum coverage percentage
include_integration = false  # Run integration tests during validation
timeout_per_test = 30     # Timeout for individual tests

[linting]
enabled = true
tools = ["flake8", "black", "isort"]  # Enabled linting tools
fail_on_warning = false   # Whether warnings should fail validation
config_files = {          # Tool-specific configuration files
  flake8 = ".flake8"
  black = "pyproject.toml"
  isort = "setup.cfg"
}

[type_checking]
enabled = true
tool = "mypy"            # Primary type checker
strict_mode = false      # Enable strict type checking mode
config_file = "mypy.ini" # Type checker configuration
incremental = true       # Use incremental type checking

[security]
enabled = true
tools = ["bandit", "safety"]  # Security scanning tools
severity_threshold = "medium"  # Minimum severity to report (low/medium/high)
ignore_patterns = ["tests/*", "docs/*"]  # Files to exclude
dependency_check = true       # Check dependencies for vulnerabilities

[git_integration]
auto_commit = true           # Automatically commit on successful validation
commit_template = "TASK-{task_id}: {description}\n\n🤖 Generated with SDD\nCo-Authored-By: Claude <noreply@anthropic.com>"
require_clean_tree = true   # Require clean working tree before validation
preserve_on_failure = true  # Preserve bundle and artifacts on validation failure